language: node_js
node_js:
- '0.10'
- '0.11'
addons:
  apt:
    packages:
    - libbluetooth-dev
before_install:
  - npm install npm@2.3.0 -g
before_deploy:
  - npm install ws browserify coffeeify
  - mkdir -p deploy/meshblu-bean/latest
  - mkdir -p deploy/meshblu-bean/$TRAVIS_TAG
  - node_modules/.bin/browserify -t coffeeify -s Connector connector.js > deploy/meshblu-bean/latest/meshblu-bean.js
  - gzip deploy/meshblu-bean/latest/meshblu-bean.js
  - mv deploy/meshblu-bean/latest/meshblu-bean.js.gz deploy/meshblu-bean/latest/meshblu-bean.js
  - cp deploy/meshblu-bean/latest/meshblu-bean.js deploy/meshblu-bean/$TRAVIS_TAG/meshblu-bean.js
deploy:
- provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key:
    secure: "BBJHUwghpX0Z4zHGwXcdG2nKZ8xsi/283fpeRpV+GhPxwXCALQINqopCmL67HBxR6RKxVWj7CFIqEKDrXC2+XOgqd2prKQ7U6qinjrrkUHLLSot6Dn9TAFCgH/GbuNq8uKwnjq1aZPDE5ZBA2rhsDC4a7xpapvRAOFI/TqTy+Jw="
  bucket: octoblu-cdn
  region: us-west-2
  skip_cleanup: true
  detect_encoding: true
  local-dir: deploy
  upload-dir: js
  on:
    tags: true
    all_branches: true
    node: '0.10'
- provider: npm
  skip_cleanup: true
  clean_up: false
  email: serveradmin@octoblu.com
  api_key:
    secure: "V3exRKgo9G2mlyTLVSiZ04u11sUTIy2+eO8ifM8enhSSeqEdlfqw7mF22ARuxUUSbFnRd34z5wREB00ZnYJZrJ4QUTont1/N6FHcPZ2Kl/ixRcea4VzTszleRGAYB/49GDTuRI1Mu93LgozI643L+eMCgfvkGOLEYA2OH2mTe7A="
  on:
    tags: true
    all_branches: true
    node: '0.11'
