language: node_js
node_js:
- '0.10'
- '0.11'
addons:
  apt:
    packages:
    - libbluetooth-dev
before_deploy:
  - npm install ws browserify coffeeify
  - mkdir -p deploy/meshblu-bean/latest
  - mkdir -p deploy/meshblu-bean/$TRAVIS_TAG
  - node_modules/.bin/browserify -t coffeeify -s Connector connector.js > deploy/meshblu-bean/latest/meshblu-bean.js
  - gzip deploy/meshblu-bean/latest/meshblu-bean.js
  - mv deploy/meshblu-bean/latest/meshblu-bean.js.gz deploy/meshblu-bean/latest/meshblu-bean.js
  - cp deploy/meshblu-bean/latest/meshblu-bean.js deploy/meshblu-bean/$TRAVIS_TAG/meshblu-bean.js
deploy:
  - provider: s3
    region: us-west-2
    access_key_id: AKIAJH2D5IPIRHYJT5IA
    secret_access_key:
      secure: "DBTCEtVrbhX5VI6Gm1sIjT04n/msJsE3qrevFCvK3/msJRKTvPfcLGa+iNCyiXZXg3Lcs2DNuH8QcWDmb3ejrQgmucYAuu6HDESfzicUE7CJVO3h/E5fbbnLd23o02D1qV9t/KUKMB+hnK8SP0JpbWtzqiZAdT5fI0AOEdKIKkI="
    bucket: octoblu-cdn
    skip_cleanup: true
    detect_encoding: true
    local-dir: deploy
    upload-dir: js
    on:
      tags: true
      all_branches: true
      node: '0.10'
  - provider: npm
    skip_cleanup: true
    email: serveradmin@octoblu.com
    api_key:
      secure: "Mz+WmbyREfee/hbbLmZmCk7YrwQtMu1WcWm6MPE/yPFJ3AJoWc/RenGTOhQX6Pn+/fLcNrHDtRjWlIuxo/xvvT1Y+MtRVbySqAQHMes7f1NTt30HameUFm1vbWlMOInPjFDtI11+KXJS8CCtBqGBIpITeht7uzGcF3Vdm4QxoGM="
    clean_up: false
    on:
      tags: true
      all_branches: true
      node: '0.11'
