sudo: false
language: node_js
cache:
  bundler: true
  directories:
    - node_modules
node_js:
- '0.10'
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libbluetooth-dev
before_deploy:
- mkdir -p deploy/meshblu-bean/latest
- mkdir -p deploy/meshblu-bean/$TRAVIS_TAG
- node_modules/.bin/browserify -s Connector connector.js > deploy/meshblu-bean/latest/meshblu-bean.js
- gzip deploy/meshblu-bean/latest/meshblu-bean.js
- mv deploy/meshblu-bean/latest/meshblu-bean.js.gz deploy/meshblu-bean/latest/meshblu-bean.js
- cp deploy/meshblu-bean/latest/meshblu-bean.js deploy/meshblu-bean/$TRAVIS_TAG/meshblu-bean.js
deploy:
- provider: npm
  skip_cleanup: true
  clean_up: false
  email: serveradmin@octoblu.com
  api_key:
    secure: ItQFt+eqduvqEOWI4EbT7TLLsBbbcrmIFOEb1xwNc65NNnEfJpJWDrLUJMlmcrdkJdGDuPHNV+JuEOMlMLMZuN2gRGRgf94ZTvBK4j2zXbDEJapZ+uG76mYN/F7oPIyIiljDphJ+q6PVCzYubhejwr7vHo5vLt3wzmaZf9swM80=
  on:
    tags: true
    all_branches: true
- provider: s3
  access_key_id: AKIAIT4X4NDGM2WVL6VA
  secret_access_key:
    secure: "EKkHE7tOHyRX+tqCDfuDRCXf87/Zl2G++LT9PMQLOh5feB4Yhr0iVuGMfPA08D2HTwHE9l4ow17j9DW0APWN6yVAhBNSfC+RKYOWiYfHSr11IapOyC77CjG5ThO7ef5SIJ22Ga1/JAbQN2+H9AmZMS+LoJHBWFLgRubApaRb5QE="
  bucket: octoblu-cdn
  region: us-west-2
  skip_cleanup: true
  detect_encoding: true
  local-dir: deploy
  upload-dir: js
  on:
    tags: true
    all_branches: true
